# Generated by Django 4.2.13 on 2024-07-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_area_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
